# define documents

In [132]:
"""
documents = ['Shipment of gold damaged in a fire',
             'Delivery of silver arrived in a silver truck',
             'Shipment of gold arrived in a truck']
             
"""


"""
documents = ["Human machine interface for lab abc computer applications",
              "A survey of user opinion of computer system response time",
              "The EPS user interface management system",
              "System and human system engineering testing of EPS",
              "Relation of user perceived response time to error measurement",
              "The generation of random binary unordered trees",
              "The intersection graph of paths in trees",
              "Graph minors IV Widths of trees and well quasi ordering",
              "Graph minors A survey"]
"""



documents = ["an airplane is flying in the sky with its landing gear down",
"a car parked on the side of the road",
"a red car parked in a parking lot",
"a red stop sign sitting on the side of a street",
"a man is playing tennis on a tennis court",
"a bathroom with a sink and a toilet",
"a woman is playing tennis on a tennis court",
"an elephant standing in a field of grass",
"a cat is laying on a bed with a stuffed animal",
"a cat that is standing in the grass",
"a cat is sitting on the floor in front of a mirror",
"a cat is sitting on a couch with a stuffed animal",
"a black cat is sitting on a chair",
"a red truck parked in front of a building",
"a black and white dog laying on the grass",
"a car is driving down the street in front of a building"]

print("length of documents: ",len(documents))

length of documents:  16


# Score term weights and construct the term-document matrix A and query matrix

In [133]:
import numpy as np

# terms
print("list all terms: ");
terms = [i for line in documents for i in line.lower().split()]
terms = sorted(list(set(terms))) # remove duplicate values and sort list alphabetically
print(terms)

# count frequency of terms
print("\nlist the term-document matrix A...>")
A = np.zeros(shape=(len(terms),len(documents)))
for i,vr in enumerate(terms):
    for j,vc in enumerate(documents):
        for k in vc.lower().split():
            if k == vr:
                A[i][j] += 1
print(A)

# construct query matrix
print("\nlist the query matrix...>")
#query = 'gold silver truck'
#query = "Human computer interaction"
query = "elephant"
q = np.zeros(shape=(len(terms),1))
for i,vr in enumerate(terms):
    for j in query.lower().split():
        if j == vr:
            q[i][0] += 1
print(q)

list all terms: 
['a', 'airplane', 'an', 'and', 'animal', 'bathroom', 'bed', 'black', 'building', 'car', 'cat', 'chair', 'couch', 'court', 'dog', 'down', 'driving', 'elephant', 'field', 'floor', 'flying', 'front', 'gear', 'grass', 'in', 'is', 'its', 'landing', 'laying', 'lot', 'man', 'mirror', 'of', 'on', 'parked', 'parking', 'playing', 'red', 'road', 'side', 'sign', 'sink', 'sitting', 'sky', 'standing', 'stop', 'street', 'stuffed', 'tennis', 'that', 'the', 'toilet', 'truck', 'white', 'with', 'woman']

list the term-document matrix A...>
[[ 0.  1.  2.  2.  2.  3.  2.  1.  3.  1.  2.  3.  2.  2.  1.  2.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0. 

# A = U \* S \* transpose_of_V

In [134]:
U, S, V = np.linalg.svd(A,full_matrices=False)
print("U = ")
print(U)
print("S = ")
print(np.diag(S))
print("V = ")
print(V)

U = 
[[  8.15384486e-01   1.50000767e-01   2.46065941e-01  -7.70303350e-02
    1.86670875e-01   1.16273941e-01   1.06647579e-02   3.08235742e-02
    5.78788138e-02  -1.84650966e-02   4.90705084e-02  -5.53265920e-02
    3.44865384e-02   1.15475057e-02   3.81417084e-02   7.17580400e-17]
 [  8.56353635e-03  -6.84891120e-02  -1.48703040e-01   1.43413762e-01
    4.94074216e-02   9.99151854e-02  -1.34532855e-01   7.44741169e-02
   -1.71212572e-02   1.18939846e-01  -1.87893870e-02   3.78554610e-02
   -9.53772346e-03   2.86817773e-02   1.66652496e-02   1.83834447e-17]
 [  2.20113419e-02  -1.18630709e-01  -1.63304210e-01   1.56511996e-01
    1.11687029e-01   1.16209866e-01   7.02549988e-02   2.96122580e-01
   -2.10783209e-02   9.22880639e-03  -1.16178145e-01   1.07233108e-01
    2.47595257e-01  -2.43941378e-02   4.66124470e-02   5.23423440e-17]
 [  4.51247986e-02   2.61914812e-02   8.48332809e-02   2.86560992e-02
   -4.54885723e-02   3.54105145e-01   1.30234360e-01  -1.14474422e-01
    2.443194

# Rank n Approximation

In [135]:
energy = 0.1
sum = np.sum(S)
rank_n = count = 0.0
for i,v in enumerate(sorted(S)):
    count += v
    if count/sum >= energy:
        rank_n = i+1
        break
print("rank_n:",rank_n)

U = np.delete(U,np.s_[rank_n:len(documents)],axis=1)
S = np.delete(S,np.s_[rank_n:len(documents)],axis=0)
V = np.delete(V,np.s_[rank_n:len(documents)],axis=0)
#U = np.delete(U, len(documents)-1, axis=1)
#S = np.delete(S, len(documents)-1, axis=0)
#V = np.delete(V, len(documents)-1, axis=0)
print("U = ")
print(U)
print("S = ")
print(np.diag(S))
print("V = ")
print(V)

rank_n: 4
U = 
[[ 0.81538449  0.15000077  0.24606594 -0.07703034]
 [ 0.00856354 -0.06848911 -0.14870304  0.14341376]
 [ 0.02201134 -0.11863071 -0.16330421  0.156512  ]
 [ 0.0451248   0.02619148  0.08483328  0.0286561 ]
 [ 0.07588339  0.11701755  0.10317681  0.18040013]
 [ 0.02927615  0.03384193  0.0865962   0.01397794]
 [ 0.03754283  0.05971778  0.04977066  0.09115578]
 [ 0.04277911  0.02584157  0.01139676  0.05547081]
 [ 0.05329497 -0.14244124  0.02833212 -0.09698403]
 [ 0.07025824 -0.19378557  0.01575572 -0.15137161]
 [ 0.15338307  0.06982963  0.05203848  0.30881585]
 [ 0.02693046  0.03349202  0.01315968  0.04079265]
 [ 0.03834057  0.05729977  0.05340615  0.08924435]
 [ 0.05388708  0.15888468 -0.24594501 -0.18216469]
 [ 0.01584865 -0.00765044 -0.00176292  0.01467816]
 [ 0.03763001 -0.15433583 -0.17606264  0.11718073]
 [ 0.02906648 -0.08584671 -0.0273596  -0.02623303]
 [ 0.01344781 -0.0501416  -0.01460117  0.01309823]
 [ 0.01344781 -0.0501416  -0.01460117  0.01309823]
 [ 0.03287493 -0

# Find the new document vector

In [136]:
# document vector
d = []
for i in range(len(documents)):
    d.append([row[i] for row in V])

print("document vector:")
for i,v in enumerate(d):
    print('d'+str(i),v)

document vector:
d0 [0.0821297686582039, -0.30247922380644016, -0.53571310459038579, 0.51075463562673062]
d1 [0.1831009659173537, -0.33509475167739905, -0.047331435023870536, -0.24261999017108979]
d2 [0.21195423554155401, -0.14161259058961603, 0.2026573997294227, -0.20304932975876303]
d3 [0.26685149594773178, -0.17888019764736462, 0.15115282112582479, -0.24988261162433942]
d4 [0.25840572402810474, 0.35085368685675045, -0.44301705457024876, -0.32438120876543125]
d5 [0.2807769488448329, 0.14946141361601564, 0.31196886769472176, 0.049781103787420067]
d6 [0.25840572402810474, 0.35085368685675056, -0.44301705457024909, -0.32438120876543142]
d7 [0.12897302133735308, -0.22144821153198979, -0.052601737522334976, 0.046648131783335198]
d8 [0.36005962811336684, 0.26374099465928935, 0.17930229325409835, 0.32464273119331694]
d9 [0.16969944802578865, -0.16655846712210143, -0.17051207644300403, 0.2279102879033536]
d10 [0.31529156265291636, -0.18976098283645146, -0.061125982940799031, 0.08415106726676

# Find the new query vector

In [137]:
# find new query vector
print("q = ")
transpose_q = q.transpose()
print(transpose_q)
print("U = ")
print(U)
print("S = ")
print(np.diag(S**-1))
new_q = np.matrix(transpose_q) * U * np.diag(S**-1)
print("new query vector = ")
print(new_q)

q = 
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]]
U = 
[[ 0.81538449  0.15000077  0.24606594 -0.07703034]
 [ 0.00856354 -0.06848911 -0.14870304  0.14341376]
 [ 0.02201134 -0.11863071 -0.16330421  0.156512  ]
 [ 0.0451248   0.02619148  0.08483328  0.0286561 ]
 [ 0.07588339  0.11701755  0.10317681  0.18040013]
 [ 0.02927615  0.03384193  0.0865962   0.01397794]
 [ 0.03754283  0.05971778  0.04977066  0.09115578]
 [ 0.04277911  0.02584157  0.01139676  0.05547081]
 [ 0.05329497 -0.14244124  0.02833212 -0.09698403]
 [ 0.07025824 -0.19378557  0.01575572 -0.15137161]
 [ 0.15338307  0.06982963  0.05203848  0.30881585]
 [ 0.02693046  0.03349202  0.01315968  0.04079265]
 [ 0.03834057  0.05729977  0.05340615  0.08924435]
 [ 0.05388708  0.15888468 -0.24594501 -0.18216469]
 [ 0.01584865 -0.00765044 -0.00176292  0.0

In [138]:
# compute similarity
sim = {}
for i,v in enumerate(d):
    sim[i] = (np.dot(new_q,v) /(np.linalg.norm(new_q) * np.linalg.norm(v)) )


print("sim =")
for i in sim:
    print(i,sim[i])

sim =
0 [[ 0.74548911]]
1 [[ 0.58259052]]
2 [[ 0.06921052]]
3 [[ 0.15863677]]
4 [[-0.33956736]]
5 [[-0.41942883]]
6 [[-0.33956736]]
7 [[ 0.91390303]]
8 [[-0.27479452]]
9 [[ 0.77779307]]
10 [[ 0.65033031]]
11 [[-0.26726099]]
12 [[-0.2298011]]
13 [[ 0.2392354]]
14 [[ 0.39085923]]
15 [[ 0.76493667]]


# Compute cosine similarity

In [139]:
# display result
import operator
sim_sort = sorted(sim.items(),key = operator.itemgetter(1),reverse = True)
print(sim_sort)

for i in sim_sort:
    print(documents[i[0]])

[(7, matrix([[ 0.91390303]])), (9, matrix([[ 0.77779307]])), (15, matrix([[ 0.76493667]])), (0, matrix([[ 0.74548911]])), (10, matrix([[ 0.65033031]])), (1, matrix([[ 0.58259052]])), (14, matrix([[ 0.39085923]])), (13, matrix([[ 0.2392354]])), (3, matrix([[ 0.15863677]])), (2, matrix([[ 0.06921052]])), (12, matrix([[-0.2298011]])), (11, matrix([[-0.26726099]])), (8, matrix([[-0.27479452]])), (6, matrix([[-0.33956736]])), (4, matrix([[-0.33956736]])), (5, matrix([[-0.41942883]]))]
an elephant standing in a field of grass
a cat that is standing in the grass
a car is driving down the street in front of a building
an airplane is flying in the sky with its landing gear down
a cat is sitting on the floor in front of a mirror
a car parked on the side of the road
a black and white dog laying on the grass
a red truck parked in front of a building
a red stop sign sitting on the side of a street
a red car parked in a parking lot
a black cat is sitting on a chair
a cat is sitting on a couch with a